### ISSUE TITLE
Library dependencies of libLLVM*so

### ISSUE THREAD

**Issue by lembergerth** [sosy-lab/llvm-j#10]
We currently get the libLLVM-3.9.1.so from the the Ubuntu 12.04 package of [LLVM](http://apt.llvm.org/).

This has the following two dependencies, that don't exist on Gentoo Linux, by default:
  - `libtinfo.so.5`
  - `libedit.so.2`

For `libtinfo.so.5`, it seems that `USE`-flag `tinfo` must be set for `sys-libs/ncurses` package.
This introduces other [challenges](https://bugs.gentoo.org/457530), though.
While this is solvable, I don't think that we should pressure our users to introduce package-related
problems into their system, if avoidable.
Thus, as an alternative, we could ship the libLLVM*.so with the `libtinfo.so.5` - it only depends on libraries
that are included with libc6:
```
> ldd /lib/x86_64-linux-gnu/libtinfo.so.5
	linux-vdso.so.1 =>  (0x00007fff189f2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efc96b9d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007efc971a6000)
```

For `libedit.so.2`, there's a [Gentoo package](https://packages.gentoo.org/packages/dev-libs/libedit).
The dependencies of `libedit.so.2` are the same as for `libtinfo.so.5`, though, + `libtinfo.so.5`:
```
> ldd /usr/lib/x86_64-linux-gnu/libedit.so.2
	linux-vdso.so.1 =>  (0x00007ffd77bf2000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f4a3ef15000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4a3eb35000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4a3f375000)
```
Since libedit doesn't seem to be a universal Linux default (as stated by the Gentoo package),
I'd vote for also deploying the `libedit.so.2` with the libLLVM*so .

**Comment by leostrakosch** [comment]
For reference, all dependencies of the `libLLVM*so` file:
```
> ldd libLLVM-3.9.1.so
	linux-vdso.so.1 =>  (0x00007fff54ebe000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fe3075cf000)
	libedit.so.2 => /usr/lib/x86_64-linux-gnu/libedit.so.2 (0x00007fe307398000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe307194000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007fe306f6b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe306d4c000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fe306b2f000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe3067a9000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe306453000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe30623c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe305e5c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe30a62b000)
```

**Comment by PhilippWendler** [comment]
I think we should ship as few binaries as possible. For LLVM itself we have the reason that the version needs to match exactly, so it would be quite a burden for users to manually keep LLVM in sync with CPAchecker. For these other libraries the reason to ship them is thus not as important and we should consider it carefully.

Are these libraries a problem on other distributions as well? Gentoo is a special case, and we can expect more manual work from Gentoo users than from users of other distributions.

Do we have convenient access to other LLVM binaries without this dependency? Could you check, e.g., the Ubuntu 14.04 binaries and the Debian binaries?

**Comment by leostrakosch** [comment]
The Debian and Ubuntu packages (up to 16.04) have the same dependencies.
There's a libtinfo package int the Arch Linux AUR (if this is any implication), thus I'd assume that
the libtinfo library is also not included with Arch Linux, by default.

The third option that we'd have is compiling the shared libraries ourselves - than, both libtinfo and libedit wouldn't be necessary.

**Comment by mchalupa** [comment]
> There's a libtinfo package in the Arch Linux AUR (if this is any implication), thus I'd assume that
the libtinfo library is also not included with Arch Linux, by default.

`libtinfo.so` is a part of ncurses in Arch Linux, so most of the users should have it
```
$ pkgfile libtinfo.so
core/ncurses
```
On Arch, a different problem may be that it already ships `libtinfo.so.6`, not `libtinfo.so.5`.

**Comment by leostrakosch** [comment]
@mchalupa could you check whether llvm-j works for you with the bundled libLLVM instead of your system's?

It should be sufficient to do a `ant unit-tests` after hiding your system's libLLVM-3.9.1.so .

**Comment by mchalupa** [comment]
Nope, but this is probably not a problem with system vs. bundled:

```
unit-tests:
    [junit] Testsuite: org.sosy_lab.llvm_j.ModuleTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.256 sec
    [junit] 
    [junit] Testcase: test_parseIR_valid(org.sosy_lab.llvm_j.ModuleTest):	Caused an ERROR
    [junit] Unable to load library 'LLVM-3.9.1': Native library (linux-x86-64/libLLVM-3.9.1.so) not found in resource path (/home/mchalupa/src/llvm-j/bin:/home/mchalupa/src/llvm-j/lib/java/build/error_prone_annotations.jar:/home/mchalupa/src/llvm-j/lib/java/runtime/animal-sniffer-annotations.jar:/home/mchalupa/src/llvm-j/lib/java/runtime/error_prone_annotations.jar:/home/mchalupa/src/llvm-j/lib/java/runtime/guava.jar:/home/mchalupa/src/llvm-j/lib/java/runtime/j2objc-annotations.jar:/home/mchalupa/src/llvm-j/lib/java/runtime/jna.jar:/home/mchalupa/src/llvm-j/lib/java/runtime/jsr305.jar:/home/mchalupa/src/llvm-j/lib/java/runtime/spotbugs-annotations.jar:/home/mchalupa/src/llvm-j/lib/java/test/animal-sniffer-annotations.jar:/home/mchalupa/src/llvm-j/lib/java/test/error_prone_annotations.jar:/home/mchalupa/src/llvm-j/lib/java/test/guava-testlib.jar:/home/mchalupa/src/llvm-j/lib/java/test/guava.jar:/home/mchalupa/src/llvm-j/lib/java/test/hamcrest-core.jar:/home/mchalupa/src/llvm-j/lib/java/test/j2objc-annotations.jar:/home/mchalupa/src/llvm-j/lib/java/test/jsr305.jar:/home/mchalupa/src/llvm-j/lib/java/test/junit.jar:/usr/share/java/apache-ant/ant-launcher.jar:/usr/share/apache-ant/lib/ant.jar:/usr/share/apache-ant/lib/ant-junit.jar:/usr/share/apache-ant/lib/ant-junit4.jar)
```

**Comment by mchalupa** [comment]
However, `ldd` still report missing dependencies:

```
	libbsd.so.0 => not found
```

**Comment by leostrakosch** [comment]
Thanks, that's exactly what I wanted to ask you next :-)

It's not that nice, but `Native library (linux-x86-64/libLLVM-3.9.1.so) not found in resource path`
is the error message for both a library that is **really** missing, and a library with unresolved dependencies.

I'll install an Arch Linux VM to check for further transitive dependencies.
Thanks for your help!

**Comment by leostrakosch** [comment]
Thanks, that's exactly what I wanted to ask you next :-)

It's not that nice, but `Native library (linux-x86-64/libLLVM-3.9.1.so) not found in resource path`
is the error message for both a library that is **really** missing, and a library with unresolved dependencies.

I'll install an Arch Linux VM to check for further transitive dependencies.
Thanks for your help!
